import { Property } from './types';

// Real Cuenca, Ecuador coordinates for various sectors
// Center of Cuenca: -2.9001, -79.0059

export const MOCK_PROPERTIES: Property[] = [
  // San Joaquín - Northwest of Cuenca, rural area
  {
    id: '1',
    slug: 'terreno-san-joaquin-vista-panoramica',
    title_es: 'Terreno con Vista Panorámica en San Joaquín',
    title_en: 'Land with Panoramic View in San Joaquín',
    description_es: 'Hermoso terreno de 1,200 m² con vista espectacular a las montañas. Ideal para construir la casa de sus sueños. Acceso pavimentado y todos los servicios básicos disponibles.',
    description_en: 'Beautiful 1,200 m² land with spectacular mountain views. Ideal for building your dream home. Paved access and all basic services available.',
    type: 'terreno',
    price: 45000,
    pricePerM2: 37.5,
    size: 1200,
    sector: 'San Joaquín',
    address: 'Vía San Joaquín, sector El Tejar',
    coordinates: { lat: -2.8823, lng: -79.0456 },
    photos: ['/images/properties/terreno-1.jpg'],
    utilities: { agua: true, luz: true, alcantarillado: false, via: true },
    documents: { iprus: true, certificadoGravamenes: true, escritura: true, lineaFabrica: true, levantamientoTopografico: true },
    agent: {
      id: 'agent-1',
      name: 'Carlos Mendoza',
      phone: '+593987654321',
      verified: true,
      responseTime: '< 2 horas',
      rating: 4.8,
      totalSales: 47,
    },
    verified: true,
    gpsVerified: true,
    featured: true,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    slug: 'casa-san-joaquin-moderna',
    title_es: 'Casa Moderna en San Joaquín',
    title_en: 'Modern House in San Joaquín',
    description_es: 'Casa de 180 m² construidos en terreno de 500 m². 3 dormitorios, 2.5 baños, sala amplia, cocina americana. Acabados de primera.',
    description_en: 'House of 180 m² built on 500 m² lot. 3 bedrooms, 2.5 bathrooms, spacious living room, American kitchen. First-class finishes.',
    type: 'casa',
    price: 145000,
    pricePerM2: 290,
    size: 500,
    sector: 'San Joaquín',
    address: 'Urbanización Los Álamos, San Joaquín',
    coordinates: { lat: -2.8756, lng: -79.0523 },
    photos: ['/images/properties/casa-1.jpg'],
    utilities: { agua: true, luz: true, alcantarillado: true, via: true },
    documents: { iprus: true, certificadoGravamenes: true, escritura: true, lineaFabrica: true, levantamientoTopografico: true },
    agent: {
      id: 'agent-1',
      name: 'Carlos Mendoza',
      phone: '+593987654321',
      verified: true,
      responseTime: '< 2 horas',
      rating: 4.8,
      totalSales: 47,
    },
    verified: true,
    gpsVerified: true,
    featured: false,
    createdAt: '2024-02-01',
  },

  // Baños - Popular thermal springs area south of Cuenca
  {
    id: '3',
    slug: 'terreno-banos-cerca-aguas-termales',
    title_es: 'Terreno cerca de Aguas Termales en Baños',
    title_en: 'Land near Hot Springs in Baños',
    description_es: 'Terreno plano de 800 m² a 5 minutos de las aguas termales de Baños. Excelente ubicación para inversión turística o residencial.',
    description_en: 'Flat 800 m² land 5 minutes from Baños hot springs. Excellent location for tourist or residential investment.',
    type: 'terreno',
    price: 52000,
    pricePerM2: 65,
    size: 800,
    sector: 'Baños',
    address: 'Sector Huizhil, Baños',
    coordinates: { lat: -2.9234, lng: -79.0678 },
    photos: ['/images/properties/terreno-2.jpg'],
    utilities: { agua: true, luz: true, alcantarillado: true, via: true },
    documents: { iprus: true, certificadoGravamenes: true, escritura: true, lineaFabrica: false, levantamientoTopografico: true },
    agent: {
      id: 'agent-2',
      name: 'María García',
      phone: '+593998765432',
      verified: true,
      responseTime: 'Mismo día',
      rating: 4.9,
      totalSales: 63,
    },
    verified: true,
    gpsVerified: true,
    featured: true,
    createdAt: '2024-01-20',
  },
  {
    id: '4',
    slug: 'departamento-banos-vista-rio',
    title_es: 'Departamento con Vista al Río en Baños',
    title_en: 'Apartment with River View in Baños',
    description_es: 'Departamento de 95 m² con hermosa vista al río. 2 dormitorios, 2 baños, balcón amplio. Edificio con áreas comunales y seguridad 24/7.',
    description_en: '95 m² apartment with beautiful river view. 2 bedrooms, 2 bathrooms, large balcony. Building with common areas and 24/7 security.',
    type: 'departamento',
    price: 89000,
    pricePerM2: 937,
    size: 95,
    sector: 'Baños',
    address: 'Av. Ricardo Durán, Baños',
    coordinates: { lat: -2.9189, lng: -79.0712 },
    photos: ['/images/properties/depto-1.jpg'],
    utilities: { agua: true, luz: true, alcantarillado: true, via: true },
    documents: { iprus: true, certificadoGravamenes: true, escritura: true, lineaFabrica: true, levantamientoTopografico: true },
    agent: {
      id: 'agent-2',
      name: 'María García',
      phone: '+593998765432',
      verified: true,
      responseTime: 'Mismo día',
      rating: 4.9,
      totalSales: 63,
    },
    verified: true,
    gpsVerified: true,
    featured: false,
    createdAt: '2024-02-10',
  },

  // Ricaurte - Growing residential area northeast
  {
    id: '5',
    slug: 'terreno-ricaurte-urbanizacion',
    title_es: 'Terreno en Urbanización Privada, Ricaurte',
    title_en: 'Land in Private Development, Ricaurte',
    description_es: 'Lote de 600 m² en urbanización cerrada con guardianía. Todos los servicios, calles adoquinadas. Ideal para familia.',
    description_en: '600 m² lot in gated community with security. All services, paved streets. Ideal for families.',
    type: 'terreno',
    price: 72000,
    pricePerM2: 120,
    size: 600,
    sector: 'Ricaurte',
    address: 'Urbanización Portal del Sol, Ricaurte',
    coordinates: { lat: -2.8634, lng: -78.9523 },
    photos: ['/images/properties/terreno-3.jpg'],
    utilities: { agua: true, luz: true, alcantarillado: true, via: true },
    documents: { iprus: true, certificadoGravamenes: true, escritura: true, lineaFabrica: true, levantamientoTopografico: true },
    agent: {
      id: 'agent-3',
      name: 'Roberto Sánchez',
      phone: '+593976543210',
      verified: true,
      responseTime: '< 2 horas',
      rating: 4.7,
      totalSales: 38,
    },
    verified: true,
    gpsVerified: true,
    featured: true,
    createdAt: '2024-01-25',
  },
  {
    id: '6',
    slug: 'casa-ricaurte-esquinera',
    title_es: 'Casa Esquinera en Ricaurte',
    title_en: 'Corner House in Ricaurte',
    description_es: 'Casa esquinera de 220 m² en terreno de 400 m². 4 dormitorios, 3 baños, patio trasero, garaje para 2 vehículos. Zona muy tranquila.',
    description_en: 'Corner house of 220 m² on 400 m² lot. 4 bedrooms, 3 bathrooms, backyard, garage for 2 vehicles. Very quiet area.',
    type: 'casa',
    price: 185000,
    pricePerM2: 462.5,
    size: 400,
    sector: 'Ricaurte',
    address: 'Calle Principal, Ricaurte Centro',
    coordinates: { lat: -2.8589, lng: -78.9567 },
    photos: ['/images/properties/casa-2.jpg'],
    utilities: { agua: true, luz: true, alcantarillado: true, via: true },
    documents: { iprus: true, certificadoGravamenes: true, escritura: true, lineaFabrica: true, levantamientoTopografico: true },
    agent: {
      id: 'agent-3',
      name: 'Roberto Sánchez',
      phone: '+593976543210',
      verified: true,
      responseTime: '< 2 horas',
      rating: 4.7,
      totalSales: 38,
    },
    verified: true,
    gpsVerified: true,
    featured: false,
    createdAt: '2024-02-05',
  },

  // Challuabamba - Upscale area east of Cuenca
  {
    id: '7',
    slug: 'terreno-challuabamba-exclusivo',
    title_es: 'Terreno Exclusivo en Challuabamba',
    title_en: 'Exclusive Land in Challuabamba',
    description_es: 'Terreno premium de 2,000 m² en la zona más exclusiva de Challuabamba. Vista al valle, acceso privado, ideal para mansión.',
    description_en: 'Premium 2,000 m² land in the most exclusive area of Challuabamba. Valley views, private access, ideal for mansion.',
    type: 'terreno',
    price: 180000,
    pricePerM2: 90,
    size: 2000,
    sector: 'Challuabamba',
    address: 'Sector Alto Challuabamba',
    coordinates: { lat: -2.8678, lng: -78.9234 },
    photos: ['/images/properties/terreno-4.jpg'],
    utilities: { agua: true, luz: true, alcantarillado: false, via: true },
    documents: { iprus: true, certificadoGravamenes: true, escritura: true, lineaFabrica: true, levantamientoTopografico: true },
    agent: {
      id: 'agent-4',
      name: 'Ana Lucía Pérez',
      phone: '+593965432109',
      verified: true,
      responseTime: 'Mismo día',
      rating: 5.0,
      totalSales: 89,
    },
    verified: true,
    gpsVerified: true,
    featured: true,
    createdAt: '2024-01-10',
  },
  {
    id: '8',
    slug: 'casa-challuabamba-lujo',
    title_es: 'Casa de Lujo en Challuabamba',
    title_en: 'Luxury House in Challuabamba',
    description_es: 'Espectacular casa de 350 m² en terreno de 1,000 m². 5 dormitorios, 4 baños, piscina, jardín, BBQ area. Vista panorámica impresionante.',
    description_en: 'Spectacular 350 m² house on 1,000 m² lot. 5 bedrooms, 4 bathrooms, pool, garden, BBQ area. Impressive panoramic view.',
    type: 'casa',
    price: 450000,
    pricePerM2: 450,
    size: 1000,
    sector: 'Challuabamba',
    address: 'Urbanización Vista Verde, Challuabamba',
    coordinates: { lat: -2.8712, lng: -78.9189 },
    photos: ['/images/properties/casa-3.jpg'],
    utilities: { agua: true, luz: true, alcantarillado: true, via: true },
    documents: { iprus: true, certificadoGravamenes: true, escritura: true, lineaFabrica: true, levantamientoTopografico: true },
    agent: {
      id: 'agent-4',
      name: 'Ana Lucía Pérez',
      phone: '+593965432109',
      verified: true,
      responseTime: 'Mismo día',
      rating: 5.0,
      totalSales: 89,
    },
    verified: true,
    gpsVerified: true,
    featured: true,
    createdAt: '2024-02-15',
  },

  // Turi - South of Cuenca with famous viewpoint
  {
    id: '9',
    slug: 'terreno-turi-mirador',
    title_es: 'Terreno cerca del Mirador de Turi',
    title_en: 'Land near Turi Viewpoint',
    description_es: 'Terreno de 1,500 m² a solo 10 minutos del famoso Mirador de Turi. Vista espectacular de toda la ciudad. Inversión segura.',
    description_en: '1,500 m² land just 10 minutes from famous Turi Viewpoint. Spectacular view of the entire city. Safe investment.',
    type: 'terreno',
    price: 67500,
    pricePerM2: 45,
    size: 1500,
    sector: 'Turi',
    address: 'Vía al Mirador, Turi',
    coordinates: { lat: -2.9234, lng: -79.0123 },
    photos: ['/images/properties/terreno-5.jpg'],
    utilities: { agua: true, luz: true, alcantarillado: false, via: true },
    documents: { iprus: true, certificadoGravamenes: true, escritura: true, lineaFabrica: false, levantamientoTopografico: true },
    agent: {
      id: 'agent-5',
      name: 'Luis Fernando Morocho',
      phone: '+593954321098',
      verified: true,
      responseTime: '24 horas',
      rating: 4.6,
      totalSales: 29,
    },
    verified: true,
    gpsVerified: true,
    featured: false,
    createdAt: '2024-01-28',
  },
  {
    id: '10',
    slug: 'casa-turi-tradicional',
    title_es: 'Casa Tradicional Renovada en Turi',
    title_en: 'Renovated Traditional House in Turi',
    description_es: 'Encantadora casa tradicional de 150 m² completamente renovada. 3 dormitorios, 2 baños, chimenea, jardín con árboles frutales.',
    description_en: 'Charming fully renovated 150 m² traditional house. 3 bedrooms, 2 bathrooms, fireplace, garden with fruit trees.',
    type: 'casa',
    price: 125000,
    pricePerM2: 357,
    size: 350,
    sector: 'Turi',
    address: 'Centro de Turi',
    coordinates: { lat: -2.9189, lng: -79.0089 },
    photos: ['/images/properties/casa-4.jpg'],
    utilities: { agua: true, luz: true, alcantarillado: true, via: true },
    documents: { iprus: true, certificadoGravamenes: true, escritura: true, lineaFabrica: true, levantamientoTopografico: true },
    agent: {
      id: 'agent-5',
      name: 'Luis Fernando Morocho',
      phone: '+593954321098',
      verified: true,
      responseTime: '24 horas',
      rating: 4.6,
      totalSales: 29,
    },
    verified: true,
    gpsVerified: true,
    featured: false,
    createdAt: '2024-02-08',
  },

  // El Valle - Large parish south of Cuenca
  {
    id: '11',
    slug: 'terreno-el-valle-agricola',
    title_es: 'Terreno Agrícola en El Valle',
    title_en: 'Agricultural Land in El Valle',
    description_es: 'Amplio terreno de 5,000 m² ideal para proyecto agrícola o residencial campestre. Agua de riego, acceso vehicular.',
    description_en: 'Large 5,000 m² land ideal for agricultural or rural residential project. Irrigation water, vehicle access.',
    type: 'terreno',
    price: 95000,
    pricePerM2: 19,
    size: 5000,
    sector: 'El Valle',
    address: 'Sector Quillopungo, El Valle',
    coordinates: { lat: -2.9456, lng: -78.9712 },
    photos: ['/images/properties/terreno-6.jpg'],
    utilities: { agua: true, luz: true, alcantarillado: false, via: true },
    documents: { iprus: true, certificadoGravamenes: true, escritura: true, lineaFabrica: false, levantamientoTopografico: true },
    agent: {
      id: 'agent-6',
      name: 'Patricia Cárdenas',
      phone: '+593943210987',
      verified: true,
      responseTime: 'Mismo día',
      rating: 4.8,
      totalSales: 52,
    },
    verified: true,
    gpsVerified: true,
    featured: false,
    createdAt: '2024-02-12',
  },
  {
    id: '12',
    slug: 'departamento-el-valle-nuevo',
    title_es: 'Departamento Nuevo en El Valle',
    title_en: 'New Apartment in El Valle',
    description_es: 'Departamento estreno de 85 m² en conjunto residencial. 2 dormitorios, 2 baños, parqueadero incluido. Excelente precio.',
    description_en: 'Brand new 85 m² apartment in residential complex. 2 bedrooms, 2 bathrooms, parking included. Excellent price.',
    type: 'departamento',
    price: 72000,
    pricePerM2: 847,
    size: 85,
    sector: 'El Valle',
    address: 'Conjunto El Jardín, El Valle',
    coordinates: { lat: -2.9389, lng: -78.9778 },
    photos: ['/images/properties/depto-2.jpg'],
    utilities: { agua: true, luz: true, alcantarillado: true, via: true },
    documents: { iprus: true, certificadoGravamenes: true, escritura: true, lineaFabrica: true, levantamientoTopografico: true },
    agent: {
      id: 'agent-6',
      name: 'Patricia Cárdenas',
      phone: '+593943210987',
      verified: true,
      responseTime: 'Mismo día',
      rating: 4.8,
      totalSales: 52,
    },
    verified: true,
    gpsVerified: true,
    featured: false,
    createdAt: '2024-01-30',
  },

  // Sayausí - West of Cuenca, mountain area
  {
    id: '13',
    slug: 'terreno-sayausi-bosque',
    title_es: 'Terreno con Bosque Nativo en Sayausí',
    title_en: 'Land with Native Forest in Sayausí',
    description_es: 'Hermoso terreno de 3,000 m² con bosque nativo y quebrada. Ideal para proyecto ecológico o casa de campo. Aire puro y tranquilidad.',
    description_en: 'Beautiful 3,000 m² land with native forest and stream. Ideal for ecological project or country house. Pure air and tranquility.',
    type: 'terreno',
    price: 78000,
    pricePerM2: 26,
    size: 3000,
    sector: 'Sayausí',
    address: 'Sector Buenos Aires, Sayausí',
    coordinates: { lat: -2.8678, lng: -79.0789 },
    photos: ['/images/properties/terreno-7.jpg'],
    utilities: { agua: true, luz: true, alcantarillado: false, via: true },
    documents: { iprus: true, certificadoGravamenes: true, escritura: true, lineaFabrica: false, levantamientoTopografico: true },
    agent: {
      id: 'agent-7',
      name: 'Jorge Ávila',
      phone: '+593932109876',
      verified: true,
      responseTime: '< 2 horas',
      rating: 4.5,
      totalSales: 21,
    },
    verified: true,
    gpsVerified: true,
    featured: false,
    createdAt: '2024-02-03',
  },
  {
    id: '14',
    slug: 'casa-sayausi-montana',
    title_es: 'Casa de Montaña en Sayausí',
    title_en: 'Mountain House in Sayausí',
    description_es: 'Acogedora casa de montaña de 200 m² en terreno de 800 m². 3 dormitorios, 2 baños, chimenea, huerto. Perfecta para amantes de la naturaleza.',
    description_en: 'Cozy 200 m² mountain house on 800 m² lot. 3 bedrooms, 2 bathrooms, fireplace, vegetable garden. Perfect for nature lovers.',
    type: 'casa',
    price: 165000,
    pricePerM2: 206.25,
    size: 800,
    sector: 'Sayausí',
    address: 'Vía Sayausí-Molleturo km 5',
    coordinates: { lat: -2.8612, lng: -79.0856 },
    photos: ['/images/properties/casa-5.jpg'],
    utilities: { agua: true, luz: true, alcantarillado: false, via: true },
    documents: { iprus: true, certificadoGravamenes: true, escritura: true, lineaFabrica: true, levantamientoTopografico: true },
    agent: {
      id: 'agent-7',
      name: 'Jorge Ávila',
      phone: '+593932109876',
      verified: true,
      responseTime: '< 2 horas',
      rating: 4.5,
      totalSales: 21,
    },
    verified: true,
    gpsVerified: true,
    featured: true,
    createdAt: '2024-01-18',
  },

  // Nulti - Eastern area of Cuenca
  {
    id: '15',
    slug: 'terreno-nulti-plano',
    title_es: 'Terreno Plano en Nulti',
    title_en: 'Flat Land in Nulti',
    description_es: 'Terreno plano de 700 m² en zona residencial de Nulti. Ideal para construcción inmediata. Todos los servicios disponibles.',
    description_en: 'Flat 700 m² land in residential area of Nulti. Ideal for immediate construction. All services available.',
    type: 'terreno',
    price: 56000,
    pricePerM2: 80,
    size: 700,
    sector: 'Nulti',
    address: 'Urbanización San Antonio, Nulti',
    coordinates: { lat: -2.8789, lng: -78.9012 },
    photos: ['/images/properties/terreno-8.jpg'],
    utilities: { agua: true, luz: true, alcantarillado: true, via: true },
    documents: { iprus: true, certificadoGravamenes: true, escritura: true, lineaFabrica: true, levantamientoTopografico: true },
    agent: {
      id: 'agent-8',
      name: 'Fernando Torres',
      phone: '+593921098765',
      verified: true,
      responseTime: 'Mismo día',
      rating: 4.7,
      totalSales: 35,
    },
    verified: true,
    gpsVerified: true,
    featured: false,
    createdAt: '2024-02-07',
  },
  {
    id: '16',
    slug: 'casa-nulti-familiar',
    title_es: 'Casa Familiar en Nulti',
    title_en: 'Family House in Nulti',
    description_es: 'Amplia casa familiar de 180 m² en terreno de 450 m². 4 dormitorios, 2.5 baños, sala de estar, comedor, cocina equipada.',
    description_en: 'Spacious 180 m² family house on 450 m² lot. 4 bedrooms, 2.5 bathrooms, living room, dining room, equipped kitchen.',
    type: 'casa',
    price: 155000,
    pricePerM2: 344.44,
    size: 450,
    sector: 'Nulti',
    address: 'Sector Centro, Nulti',
    coordinates: { lat: -2.8823, lng: -78.8967 },
    photos: ['/images/properties/casa-6.jpg'],
    utilities: { agua: true, luz: true, alcantarillado: true, via: true },
    documents: { iprus: true, certificadoGravamenes: true, escritura: true, lineaFabrica: true, levantamientoTopografico: true },
    agent: {
      id: 'agent-8',
      name: 'Fernando Torres',
      phone: '+593921098765',
      verified: true,
      responseTime: 'Mismo día',
      rating: 4.7,
      totalSales: 35,
    },
    verified: true,
    gpsVerified: true,
    featured: false,
    createdAt: '2024-01-22',
  },

  // Additional varied listings
  {
    id: '17',
    slug: 'departamento-ricaurte-moderno',
    title_es: 'Departamento Moderno en Ricaurte',
    title_en: 'Modern Apartment in Ricaurte',
    description_es: 'Departamento de 110 m² con diseño contemporáneo. 3 dormitorios, 2 baños, balcón, parqueadero. Edificio con gimnasio y áreas verdes.',
    description_en: '110 m² apartment with contemporary design. 3 bedrooms, 2 bathrooms, balcony, parking. Building with gym and green areas.',
    type: 'departamento',
    price: 115000,
    pricePerM2: 1045,
    size: 110,
    sector: 'Ricaurte',
    address: 'Av. Principal de Ricaurte',
    coordinates: { lat: -2.8612, lng: -78.9489 },
    photos: ['/images/properties/depto-3.jpg'],
    utilities: { agua: true, luz: true, alcantarillado: true, via: true },
    documents: { iprus: true, certificadoGravamenes: true, escritura: true, lineaFabrica: true, levantamientoTopografico: true },
    agent: {
      id: 'agent-3',
      name: 'Roberto Sánchez',
      phone: '+593976543210',
      verified: true,
      responseTime: '< 2 horas',
      rating: 4.7,
      totalSales: 38,
    },
    verified: true,
    gpsVerified: true,
    featured: false,
    createdAt: '2024-02-14',
  },
  {
    id: '18',
    slug: 'terreno-banos-comercial',
    title_es: 'Terreno Comercial en Baños',
    title_en: 'Commercial Land in Baños',
    description_es: 'Terreno comercial de 400 m² sobre vía principal. Alto tráfico vehicular y peatonal. Ideal para negocio turístico.',
    description_en: '400 m² commercial land on main road. High vehicle and pedestrian traffic. Ideal for tourist business.',
    type: 'terreno',
    price: 85000,
    pricePerM2: 212.5,
    size: 400,
    sector: 'Baños',
    address: 'Av. Ricardo Durán, sector comercial',
    coordinates: { lat: -2.9156, lng: -79.0645 },
    photos: ['/images/properties/terreno-9.jpg'],
    utilities: { agua: true, luz: true, alcantarillado: true, via: true },
    documents: { iprus: true, certificadoGravamenes: true, escritura: true, lineaFabrica: true, levantamientoTopografico: true },
    agent: {
      id: 'agent-2',
      name: 'María García',
      phone: '+593998765432',
      verified: true,
      responseTime: 'Mismo día',
      rating: 4.9,
      totalSales: 63,
    },
    verified: true,
    gpsVerified: true,
    featured: true,
    createdAt: '2024-02-11',
  },
  {
    id: '19',
    slug: 'casa-challuabamba-minimalista',
    title_es: 'Casa Minimalista en Challuabamba',
    title_en: 'Minimalist House in Challuabamba',
    description_es: 'Elegante casa minimalista de 280 m². Arquitectura contemporánea, espacios amplios, acabados de lujo. 4 dormitorios con baño privado.',
    description_en: 'Elegant 280 m² minimalist house. Contemporary architecture, spacious rooms, luxury finishes. 4 bedrooms with private bathroom.',
    type: 'casa',
    price: 320000,
    pricePerM2: 457,
    size: 700,
    sector: 'Challuabamba',
    address: 'Condominio Las Palmas, Challuabamba',
    coordinates: { lat: -2.8745, lng: -78.9156 },
    photos: ['/images/properties/casa-7.jpg'],
    utilities: { agua: true, luz: true, alcantarillado: true, via: true },
    documents: { iprus: true, certificadoGravamenes: true, escritura: true, lineaFabrica: true, levantamientoTopografico: true },
    agent: {
      id: 'agent-4',
      name: 'Ana Lucía Pérez',
      phone: '+593965432109',
      verified: true,
      responseTime: 'Mismo día',
      rating: 5.0,
      totalSales: 89,
    },
    verified: true,
    gpsVerified: true,
    featured: true,
    createdAt: '2024-02-16',
  },
  {
    id: '20',
    slug: 'terreno-el-valle-esquinero',
    title_es: 'Terreno Esquinero en El Valle',
    title_en: 'Corner Lot in El Valle',
    description_es: 'Terreno esquinero de 500 m² con dos frentes. Excelente ubicación cerca del centro de El Valle. Ideal para proyecto comercial o residencial.',
    description_en: '500 m² corner lot with two fronts. Excellent location near El Valle center. Ideal for commercial or residential project.',
    type: 'terreno',
    price: 65000,
    pricePerM2: 130,
    size: 500,
    sector: 'El Valle',
    address: 'Esquina Av. Principal con Calle Sucre',
    coordinates: { lat: -2.9323, lng: -78.9823 },
    photos: ['/images/properties/terreno-10.jpg'],
    utilities: { agua: true, luz: true, alcantarillado: true, via: true },
    documents: { iprus: true, certificadoGravamenes: true, escritura: true, lineaFabrica: true, levantamientoTopografico: true },
    agent: {
      id: 'agent-6',
      name: 'Patricia Cárdenas',
      phone: '+593943210987',
      verified: true,
      responseTime: 'Mismo día',
      rating: 4.8,
      totalSales: 52,
    },
    verified: true,
    gpsVerified: true,
    featured: false,
    createdAt: '2024-02-09',
  },
];

// Helper function to get property by slug
export function getPropertyBySlug(slug: string): Property | undefined {
  return MOCK_PROPERTIES.find((p) => p.slug === slug);
}

// Helper function to filter properties
export function filterProperties(
  properties: Property[],
  filters: {
    type?: string;
    priceMin?: number;
    priceMax?: number;
    sizeMin?: number;
    sizeMax?: number;
    sector?: string;
    verifiedOnly?: boolean;
    hasAgua?: boolean;
    hasLuz?: boolean;
    hasAlcantarillado?: boolean;
    hasVia?: boolean;
  }
): Property[] {
  return properties.filter((property) => {
    if (filters.type && property.type !== filters.type) return false;
    if (filters.priceMin && property.price < filters.priceMin) return false;
    if (filters.priceMax && property.price > filters.priceMax) return false;
    if (filters.sizeMin && property.size < filters.sizeMin) return false;
    if (filters.sizeMax && property.size > filters.sizeMax) return false;
    if (filters.sector && property.sector !== filters.sector) return false;
    if (filters.verifiedOnly && !property.verified) return false;
    if (filters.hasAgua && !property.utilities.agua) return false;
    if (filters.hasLuz && !property.utilities.luz) return false;
    if (filters.hasAlcantarillado && !property.utilities.alcantarillado) return false;
    if (filters.hasVia && !property.utilities.via) return false;
    return true;
  });
}
